In [20]:
import  numpy as np
np.set_printoptions(suppress = True)

In [21]:
def addEdge(graph, u, v):
    graph[u - 1][v - 1] = 1

In [22]:
# 节点个数，转移概率
n = 9
epsilon, max_iter = 1e-6, 200

# 首先生成一个n*n的矩阵，全部初始化为0
linkMatrix = np.zeros((n,n))

# 根据图添加边
addEdge(linkMatrix, 1, 2)
addEdge(linkMatrix, 2, 4)
addEdge(linkMatrix, 2, 7)
addEdge(linkMatrix, 3, 7)
addEdge(linkMatrix, 4, 1)
addEdge(linkMatrix, 4, 5)
addEdge(linkMatrix, 5, 6)
addEdge(linkMatrix, 5, 9)
addEdge(linkMatrix, 8, 7)
addEdge(linkMatrix, 8, 9)

print(linkMatrix)

# 设置hub和authority初始化
h = np.array([1 / n] * n)
a = np.array([0] * n)

# 打印初始化
i = 0
print(f'h{i} = {np.around(h, decimals = 3)}\na{i} = {np.around(a, decimals = 3)}\n')

for i in range(1, max_iter):
    # 迭代
    a_temp = np.dot(linkMatrix.T, h)
    h_temp = np.dot(linkMatrix, a_temp)
    
    # 归一化
    a_temp = a_temp / np.sum(a_temp)
    h_temp = h_temp / np.sum(h_temp)    
    
    if np.sum(np.abs(h - h_temp)) + np.sum(np.abs(a - a_temp)) < epsilon:
        break
    else: 
        h, a  = h_temp, a_temp
        print(f'h{i} = {np.around(h, decimals = 4)}\na{i} = {np.around(a, decimals = 4)}\n')

[[0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
h0 = [0.111 0.111 0.111 0.111 0.111 0.111 0.111 0.111 0.111]
a0 = [0 0 0 0 0 0 0 0 0]

h1 = [0.0556 0.2222 0.1667 0.1111 0.1667 0.     0.     0.2778 0.    ]
a1 = [0.1 0.1 0.  0.1 0.1 0.1 0.3 0.  0.2]

h2 = [0.0156 0.25   0.1875 0.0625 0.1719 0.     0.     0.3125 0.    ]
a2 = [0.0625 0.0312 0.     0.125  0.0625 0.0938 0.375  0.     0.25  ]

h3 = [0.0041 0.2645 0.1983 0.0331 0.1736 0.     0.     0.3264 0.    ]
a3 = [0.0348 0.0087 0.     0.1391 0.0348 0.0957 0.4174 0.     0.2696]

h4 = [0.0011 0.2719 0.2036 0.0171 0.1738 0.     0.     0.3326 0.    ]
a4 = [0.0184 0.0023 0.     0.1471 0.0184 0.0966 0.4391 0.     0.2782]

h5 = [0.0003 0.2756 0.2063 0.0087 0.1736 0.     0.     0.3355 0.    ]
a5 = [0.0095 0.0006 0.     0.1514 0