In [1]:
import  numpy as np

In [2]:
def addEdge(graph, u, v):
    graph[u - 1][v - 1] = 1

In [3]:
# 节点个数，转移概率
n, alpha = 3, 0.05
epsilon, max_iter = 1e-6, 200

# 首先生成一个n*n的矩阵，全部初始化为0
linkMatrix = np.zeros((n, n))

# 根据图添加边
addEdge(linkMatrix, 1, 2)
addEdge(linkMatrix, 1, 3)
addEdge(linkMatrix, 2, 3)
addEdge(linkMatrix, 3, 2)

print(linkMatrix)

transitionProbabilityMatrix = np.array(
    [line / np.sum(line) for line in linkMatrix])
transitionMatrixWithTeleporting = transitionProbabilityMatrix * \
    (1 - alpha) + alpha / n

print(transitionMatrixWithTeleporting)
# 初始化起始状态
x = np.array([1/n] * n)
print(f'x = {x}')

for i in range(1, max_iter):
    x_temp = np.dot(x, transitionMatrixWithTeleporting)
    print(f'xP{i} = {np.around(x_temp, decimals=3)}')
    if np.sum(np.abs(x - x_temp)) < epsilon:
        break
    else:
        x = x_temp


[[0. 1. 1.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[0.01666667 0.49166667 0.49166667]
 [0.01666667 0.01666667 0.96666667]
 [0.01666667 0.96666667 0.01666667]]
x = [0.33333333 0.33333333 0.33333333]
xP1 = [0.017 0.492 0.492]
xP2 = [0.017 0.492 0.492]
